# Generated by Django 5.0.3 on 2024-03-15 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='agendaPersonal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=65)),
                ('last_name', models.CharField(max_length=65)),
                ('address', models.CharField(max_length=65)),
                ('city', models.CharField(max_length=65)),
                ('age', models.IntegerField()),
            ],
        ),
    ]
